name: Build Docker image and push to registry

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@master
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: mwalliczek/jacoco2cobertura:latest
